version: 2.1

# -------------------------------------------------------------------------------------------------
# ORBS
# -------------------------------------------------------------------------------------------------

orbs:
  frontend: ornikar/frontend-orb@8.8.1

# -------------------------------------------------------------------------------------------------
# WORKFLOWS
# -------------------------------------------------------------------------------------------------

workflows:
  main-workflow:
    jobs:
      - frontend/checks:
          name: checks
          check-package-script-path: 'scripts/check-packagejson.mjs'

      - frontend/lint-src:
          name: lint
          use-cache: false
          cache-version: none
          run-tsc: false
          run-stylelint: false

      # release
      - hold-release:
          type: approval
          filters:
            branches:
              only: main

      - frontend/monorepo-release:
          npm-publish: true
          no-private: true
          context: npm-publish
          requires:
            - checks
            - lint
            - hold-release
          filters:
            branches:
              only: main
