version: 2.1

# -------------------------------------------------------------------------------------------------
# PIPELINE PARAMS
# -------------------------------------------------------------------------------------------------

parameters:
  cache-version:
    type: string
    default: v1

# -------------------------------------------------------------------------------------------------
# ORBS
# -------------------------------------------------------------------------------------------------

orbs:
  frontend: ornikar/frontend-orb@2.0.0

# -------------------------------------------------------------------------------------------------
# COMMANDS
# -------------------------------------------------------------------------------------------------

commands:
  checkout-and-restore-cache:
    steps:
      - checkout
      - frontend/restore-cache: &restore-cache-params
          version: << pipeline.parameters.cache-version >>
          cache-name: dependencies

# -------------------------------------------------------------------------------------------------
# JOBS
# -------------------------------------------------------------------------------------------------

jobs:
  dependencies:
    executor: frontend/node
    steps:
      - checkout
      - frontend/dependencies:
          before-install:
            - frontend/restore-cache: *restore-cache-params
          after-install:
            - save_cache:
                key: << pipeline.parameters.cache-version >>-node12-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
                paths:
                  - node_modules
                  - '@ornikar/eslint-config/node_modules'
                  - '@ornikar/eslint-config-babel/node_modules'
                  - '@ornikar/eslint-config-babel-use/node_modules'
                  - '@ornikar/eslint-config-formatjs/node_modules'
                  - '@ornikar/eslint-config-node/node_modules'
                  - '@ornikar/eslint-config-react/node_modules'
                  - '@ornikar/eslint-config-typescript/node_modules'
                  - '@ornikar/eslint-config-typescript-react/node_modules'

# -------------------------------------------------------------------------------------------------
# WORKFLOWS
# -------------------------------------------------------------------------------------------------

workflows:
  version: 2

  main-workflow:
    jobs:
      - dependencies

      - frontend/checks:
          cache-version: << pipeline.parameters.cache-version >>
          run-yarn-check: true
          requires:
            - dependencies

      - frontend/lint-prettier:
          cache-version: << pipeline.parameters.cache-version >>
          requires:
            - dependencies

      - frontend/lint-eslint:
          cache-version: << pipeline.parameters.cache-version >>
          requires:
            - dependencies

      # release
      - hold-release:
          type: approval
          filters:
            branches:
              only: master
      - frontend/lerna-publish:
          cache-version: << pipeline.parameters.cache-version >>
          context: npm-publish
          requires:
            - dependencies
            - frontend/checks
            - frontend/lint-prettier
            - frontend/lint-eslint
            - hold-release
          filters:
            branches:
              only: master
